language: node_js
node_js:
  - 'stable'
addons:
  firefox: "43.0"
before_script:
  - npm install -g testee
  - npm install grunt-cli -g
  - echo "Starting framebuffer"
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
  - echo "Extracting firefox and setting PATH variable..."
  - tar -xjf /tmp/firefox-43.0.tar.bz2 --directory /tmp
  - export PATH="/tmp/firefox:$PATH"
  - echo "Using firefox version `firefox --version`"

after_success:
  grunt ftpDeploy00

 # whitelist
branches:
  only:
    - master
